name: build-and-deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/15 * * * *"   # every 15 min (UTC, best-effort)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml
      - run: python build.py
      - name: ensure CNAME
        run: |
          mkdir -p public
          echo "nortreport.com" > public/CNAME
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
